import flet as ft

from src.ui.catalog import (  # noqa: F401  (re-exportado para compatibilidad)
    CATALOGO,
    DOC_HISTORICO,
    DOC_HISTORICO_LABEL,
    HistorialConfig,
    MODALIDAD_CONSOLIDADO,
    MODALIDAD_INDIVIDUAL,
    ORDEN_CASOS,
    build_documento_nombre,
    build_expediente_id,
    caso_de_legacy,
)


# ── Configuración de presentación de cada tipo de gestión ───────────────────
# Cada entrada define cómo se muestra y qué insumos requiere el caso en la UI.
# El catálogo canónico completo (nombres, códigos de modalidad, histórico)
# vive en src/ui/catalog.py y se importa aquí para compatibilidad.

TIPO_CONFIG = {
    "diferencia_precio": {
        "grupo": "Historial + Lista de Precios",
        "label": "Diferencia de Costo",
        "icon": ft.Icons.PRICE_CHANGE_OUTLINED,
        "descripcion": "Compara precio historico masivo vs lista de precios con filtros por vendedor, cliente y fechas.",
        "necesita_lista": True,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
    "diferencia_cantidad": {
        "grupo": "Historial + Lista de Precios",
        "label": "Cantidad Determinada",
        "icon": ft.Icons.CALCULATE_OUTLINED,
        "descripcion": "Precio de lista vs histórico sobre una cantidad exacta por SKU; reparto FIFO/LIFO y alerta si excede lo facturado.",
        "necesita_lista": True,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
    "descuento_precio": {
        "grupo": "Historial + Archivo Externo",
        "label": "Descuento Comercial",
        "icon": ft.Icons.LOW_PRIORITY_OUTLINED,
        "descripcion": "Aplica % descuento por SKU sobre precio historico. La modalidad Individual aplica a una sola factura; Consolidado a todo el fragmento.",
        "necesita_lista": False,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
    "bonificacion_promocion": {
        "grupo": "Solo Historial",
        "label": "Promocion 12+1",
        "icon": ft.Icons.CARD_GIFTCARD_OUTLINED,
        "descripcion": "Calcula bonificaciones por mecanica (12+1, etc).",
        "necesita_lista": False,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": True,
        "tiene_periodo": True,
        "tiene_mecanica": True,
        "tiene_meta": False,
    },
    "rebate_volumen": {
        "grupo": "Solo Historial",
        "label": "Concurso de Venta / Meta",
        "icon": ft.Icons.TRENDING_UP_OUTLINED,
        "descripcion": "Calcula % de rebate sobre metas por vendedor, cliente, lineas y periodo.",
        "necesita_lista": False,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": True,
        "tiene_mecanica": False,
        "tiene_meta": True,
    },
    "anular_factura": {
        "grupo": "Solo Historial",
        "label": "Anular Factura",
        "icon": ft.Icons.CANCEL_OUTLINED,
        "descripcion": "Genera NC por el 100% del valor de una factura especifica.",
        "necesita_lista": False,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
    "feria_preventa": {
        "grupo": "Historial + Archivo Externo",
        "label": "Feria / Preventa / Evento",
        "icon": ft.Icons.STORE_OUTLINED,
        "descripcion": "Asigna facturas de sustento LIFO desde archivos de requerimientos.",
        "necesita_lista": False,
        "necesita_requerimientos": True,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
    "descuento_factura": {
        "grupo": "Historial + Archivo Externo",
        "label": "Descuento Otorgado",
        "icon": ft.Icons.PERCENT_OUTLINED,
        "descripcion": "Aplica % descuento por SKU a una factura especifica.",
        "necesita_lista": False,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
    "diferencia_stock": {
        "grupo": "Historial + Lista + Stock",
        "label": "Reconocimiento por Stock",
        "icon": ft.Icons.INVENTORY_2_OUTLINED,
        "descripcion": "Un solo archivo por SKU con CANTIDAD, PRECIO_BASE y cadena de descuentos. Reparto FIFO/LIFO contra las facturas del caso y alerta si excede lo facturado.",
        "necesita_lista": True,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
    "devolucion_fisica": {
        "grupo": "Historial + Archivo Externo",
        "label": "Devolucion Fisica",
        "icon": ft.Icons.REPLAY_OUTLINED,
        "descripcion": "Asigna cantidades devueltas contra facturas por LIFO. Precio neto si hay NC total previa.",
        "necesita_lista": False,
        "necesita_requerimientos": False,
        "tiene_modalidad": False,
        "tiene_sku": False,
        "tiene_periodo": False,
        "tiene_mecanica": False,
        "tiene_meta": False,
    },
}

# ── Naming: fuente unica de verdad para titulos, justificaciones y filenames ─
# Tres sistemas de naming coexistian (TIPO_CONFIG, LABEL_TIPO del Excel, labels_tipo del DOCX);
# NAMING consolida todo. Excel, DOCX, filename y configuracion leen de aqui.

NAMING = {
    "diferencia_precio": {
        "titulo": "NC por Diferencia de Costo",
        "subtitulo": "Comparación precio atendido vs lista vigente por período",
        "docx_titulo": "Informe de Sustento — Diferencia de Costo",
        "justificacion": "Se verificaron las facturas del período comparando el precio atendido con la condición comercial vigente de la lista de precios asignada, identificando las diferencias por artículo que sustentan la solicitud de Nota de Crédito.",
        "granularidad": "por_factura",
        "nombre_corto": "DiferenciaCosto",
    },
    "diferencia_cantidad": {
        "titulo": "NC por Cantidad Determinada",
        "subtitulo": "Precio de lista vs histórico sobre cantidad exacta por SKU",
        "docx_titulo": "Informe de Sustento — Cantidad Determinada",
        "justificacion": "Se verificaron las facturas del período contra la lista de precios vigente aplicando la cantidad exacta por SKU del evento, con reparto FIFO/LIFO entre los documentos que sustentan la solicitud de Nota de Crédito.",
        "granularidad": "configurable",
        "nombre_corto": "CantDeterminada",
    },
    "descuento_precio": {
        "titulo": "NC por Descuento Comercial",
        "subtitulo": "Descuento por SKU (%) aplicado al precio histórico",
        "docx_titulo": "Informe de Sustento — Descuento Comercial",
        "justificacion": "Se identificaron los artículos vendidos a los cuales no se aplicó el descuento acordado por SKU, calculando la omisión del valor correspondiente.",
        "granularidad": "por_factura",
        "requiere_fechas": True,
        "nombre_corto": "DescuentoComercial",
    },
    "descuento_factura": {
        "titulo": "NC por Descuento Comercial",
        "subtitulo": "Descuento por factura (%) aplicado al precio histórico",
        "docx_titulo": "Informe de Sustento — Descuento Comercial por Factura",
        "justificacion": "Se identificaron las facturas a las cuales no se aplicó el descuento acordado, calculando la omisión del valor correspondiente.",
        "granularidad": "por_factura",
        "requiere_fechas": True,
        "nombre_corto": "DescuentoFactura",
    },
    "diferencia_stock": {
        "titulo": "NC por Reconocimiento de Stock",
        "subtitulo": "Diferencia de precio vs lista sobre la cantidad determinada por SKU",
        "docx_titulo": "Informe de Sustento — Reconocimiento de Stock",
        "justificacion": "Se compararon los precios históricos de compra con el precio de lista vigente sobre la cantidad determinada por SKU, aplicando la asignación seleccionada (FIFO/LIFO) contra las facturas del caso para calcular la diferencia a reconocer.",
        "granularidad": "configurable",
        "requiere_fechas": False,
        "nombre_corto": "ReconocStock",
    },
    "feria_preventa": {
        "titulo": "NC por Feria / Preventa / Evento",
        "subtitulo": "Asignación LIFO de facturas de sustento",
        "docx_titulo": "Informe de Sustento — Feria / Preventa / Evento",
        "justificacion": "Se asignaron facturas históricas como sustento de los requerimientos del evento/preventa mediante asignación LIFO, calculando la diferencia de precio reconocida.",
        "granularidad": "consolidado",
        "requiere_fechas": False,
        "nombre_corto": "FeriaPreventa",
    },
    "bonificacion_promocion": {
        "titulo": "NC por Promoción 12+1",
        "subtitulo": "Bonificación por mecánica promocional",
        "docx_titulo": "Informe de Sustento — Promoción 12+1",
        "justificacion": "Se verificaron los volúmenes comprados por artículo en el período contra la mecánica promocional acordada, calculando las unidades bonificadas y su valor.",
        "granularidad": "consolidado",
        "requiere_fechas": True,
        "nombre_corto": "PromoBonif",
    },
    "rebate_volumen": {
        "titulo": "NC por Concurso de Venta — Meta Cumplida",
        "subtitulo": "Rebate % sobre volumen objetivo por línea",
        "docx_titulo": "Informe de Sustento — Concurso de Venta / Meta",
        "justificacion": "Se verificaron los volúmenes de venta por línea contra la meta acordada, calculando el porcentaje de rebate sobre el volumen objetivo cumplido.",
        "granularidad": "consolidado",
        "requiere_fechas": True,
        "nombre_corto": "RebateMeta",
    },
    "anular_factura": {
        "titulo": "NC por Anulación de Factura",
        "subtitulo": "Cancelación del 100% del valor",
        "docx_titulo": "Informe de Sustento — Anulación de Factura",
        "justificacion": "Se anuló el 100% del valor de la factura referenciada, generando la Nota de Crédito correspondiente al total facturado.",
        "granularidad": "por_factura",
        "requiere_fechas": False,
        "nombre_corto": "Anulacion",
    },
    "devolucion_fisica": {
        "titulo": "NC por Devolución Física",
        "subtitulo": "Asignación LIFO de mercadería devuelta contra facturas",
        "docx_titulo": "Informe de Sustento — Devolución Física",
        "justificacion": "Se asignaron las cantidades devueltas contra facturas históricas del mismo artículo mediante asignación LIFO, calculando el valor a reconocer al precio neto (descontando NCs totales previas).",
        "granularidad": "por_factura",
        "requiere_fechas": False,
        "nombre_corto": "DevolucionFis",
    },
}


ESTRATEGIA_POR_TIPO = {
    "diferencia_precio": ("PriceDifference", ""),
    # VRS y su alias oculto `diferencia_cantidad` comparten motor.
    "diferencia_stock": ("CantidadDeterminada", ""),
    "diferencia_cantidad": ("CantidadDeterminada", ""),
    "descuento_precio": ("PriceDifference", "discount_period"),
    "bonificacion_promocion": ("PromotionBonus", ""),
    "rebate_volumen": ("VolumeRebate", ""),
    "anular_factura": ("CancelInvoice", ""),
    "feria_preventa": ("FeriaPreventa", ""),
    "devolucion_fisica": ("DevolucionFisica", ""),
}
